# File: configuration.yaml
# Version: v1.0.3 — 2025-06-11
# Description: Core Home Assistant configuration file with modular includes

# ================================
# Core Settings & Integrations
# ================================

default_config:

# Enable default UI and dashboards
my:

# Template sensors, binary sensors, etc.
template: !include_dir_merge_list templates/

# Custom themes and frontend tweaks
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js

# Automation, script, and scene includes
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# ================================
# Voice Assistant Integration
# ================================

# Alexa integration
alexa:
  smart_home:
    locale: en-US
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: amzn1.application-oa2-client.4ed7ca5f8da6451296f04bba9166c21d
    client_secret: amzn1.oa2-cs.v1.0c8090175561435b9bc7f46fde8b3d56d96d1005be24a4c0562cce6e703cd6c4
    filter:
      include_entities:
        - light.bedroom_primary_hue_group_switch

# ================================
# HomeKit Integration (Filtered)
# ================================
homekit:
  filter:
    include_entities:
      # Hue groups
      - light.kitchen_hue_group_switch
      - light.livingroom_switch
      - light.bedroom_primary_hue_group_switch
      - light.patio_hue_group_switch
      - light.downstairs_inside
      - light.downstairs_hue_group
      - light.upstairs_hue_group

      # Lutron lights
      - light.office_desk_lamp
      - light.bedroom_lamp_left
      - light.bedroom_lamp_right
      - light.livingroom_lamp_1
      - light.livingroom_lamp_2
      - light.kitchen_ceiling_lights
      - light.hallway_ceiling_lights

      # Other non-group lights
      - light.bathroom_primary_ceiling
      - light.bathroom_guest_ceiling
      - light.stairs_lights
      - light.entryway_ceiling
      - light.guest_bedroom_ceiling

    exclude_domains:
      - media_player
      - camera
      - climate
      - sensor
      - input_boolean
      - automation
      - binary_sensor

  entity_config:
    light.downstairs_inside:
      name: "Downstairs Lights"
    light.kitchen_hue_group_switch:
      name: "Kitchen Lights"
    light.livingroom_switch:
      name: "Living Room Lights"
    light.bedroom_primary_hue_group_switch:
      name: "Bedroom Lights"
    light.patio_hue_group_switch:
      name: "Patio Lights"

# ================================
# Authentication & File Access
# ================================

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.50.0/24
    - type: homeassistant
  allowlist_external_dirs:
    - "/config"

# ================================
# HTTP & Proxy Settings
# ================================

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.50.0/24
    - 127.0.0.1
    - 192.168.50.190
    - 192.168.50.34

# ================================
# Logging Levels
# ================================

logger:
  default: warning
  logs:
    custom_components.localtuya: debug

# ================================
# Shell Commands
# ================================

shell_command:
  nightly_git_backup: bash /config/git-nightly.sh
