# Enable default integrations like the dashboard, history, and logs
my:

# Include template sensors like binary_sensor.motion_lighting_globally_allowed
template: !include templates.yaml

# Load custom themes for the frontend
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url: #Custom brand icons from HACS
    - /local/community/custom-brand-icons/custom-brand-icons.js

# Split configurations for automations, scripts, and scenes
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Alexa integration for smart home devices
alexa:
  smart_home:
    locale: en-US
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: amzn1.application-oa2-client.4ed7ca5f8da6451296f04bba9166c21d
    client_secret: amzn1.oa2-cs.v1.0c8090175561435b9bc7f46fde8b3d56d96d1005be24a4c0562cce6e703cd6c4
    filter:
      include_entities:
        - light.bedroom_primary_hue_group_switch
#      include_entity_globs:
#        - binary_sensor.*_motion
#      include_domains:
#        - switch
#      exclude_entities:
#        - switch.outside
#    entity_config:
#      light.kitchen:
#        name: "Custom Name for Alexa"
#        description: "The light in the kitchen"
#      switch.stairs:
#        display_categories: LIGHT

# Authentication configuration for trusted networks
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.50.0/24 # Allow bypass for local network
    - type: homeassistant
  allowlist_external_dirs:
    - "/config"

# HTTP proxy and trusted proxies for secure remote access
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.50.0/24 # Local network subnet
    - 127.0.0.1 # Localhost (if applicable)
    - 192.168.50.190 #local ip
    - 192.168.50.34 # Niginx Proxy Manager

# Enable detailed debugging for LocalTuya
logger:
  default: warning
  logs:
    custom_components.localtuya: debug
