# ================================
# Core Settings & Integrations
# ================================

# Enable default UI and dashboards
my:

# Template sensors, binary sensors, etc.
template: !include templates.yaml

# Custom themes and frontend tweaks
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:  # HACS custom icons
    - /local/community/custom-brand-icons/custom-brand-icons.js

# Automation, script, and scene includes
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# ================================
# Voice Assistant Integration
# ================================

# Alexa integration
alexa:
  smart_home:
    locale: en-US
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: amzn1.application-oa2-client.4ed7ca5f8da6451296f04bba9166c21d
    client_secret: amzn1.oa2-cs.v1.0c8090175561435b9bc7f46fde8b3d56d96d1005be24a4c0562cce6e703cd6c4
    filter:
      include_entities:
        - light.bedroom_primary_hue_group_switch
#      include_entity_globs:
#        - binary_sensor.*_motion
#      include_domains:
#        - switch
#      exclude_entities:
#        - switch.outside
#    entity_config:
#      light.kitchen:
#        name: "Custom Name for Alexa"
#        description: "The light in the kitchen"
#      switch.stairs:
#        display_categories: LIGHT

# ================================
# Authentication & File Access
# ================================

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.50.0/24  # Allow bypass for local network
    - type: homeassistant
  allowlist_external_dirs:
    - "/config"  # Allow shell_command access to config files

# ================================
# HTTP & Proxy Settings
# ================================

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.50.0/24     # Local network subnet
    - 127.0.0.1           # Localhost
    - 192.168.50.190      # MotionEye or similar
    - 192.168.50.34       # Nginx Proxy Manager

# ================================
# Logging Levels
# ================================

logger:
  default: warning
  logs:
    custom_components.localtuya: debug

# ================================
# Shell Commands
# ================================

shell_command:
  nightly_git_backup: bash /config/git-nightly.sh
