# File: templates.yaml
# Version: v1.0.2
# Last Updated: 2025-06-11
# Description: Entry point for all template integrations

binary_sensor: !include_dir_merge_list templates/binary_sensors/
sensor: !include_dir_merge_list templates/sensors/
